FROM mcr.microsoft.com/powershell:latest AS builder

USER root

RUN apt-get update && apt-get install -y \
    git \
    golang-go \
    gcc-mingw-w64-x86-64 \
    g++-mingw-w64-x86-64 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN mkdir -p /root/.config/powershell && \
    echo '$env:CGO_ENABLED="1"' >> /root/.config/powershell/Microsoft.PowerShell_profile.ps1 && \
    echo '$env:GOOS="windows"' >> /root/.config/powershell/Microsoft.PowerShell_profile.ps1 && \
    echo '$env:CC="x86_64-w64-mingw32-gcc"' >> /root/.config/powershell/Microsoft.PowerShell_profile.ps1


RUN cd ./src/go && \
    sed -i '/^go /d' go.mod && \
    go mod tidy && \
    go build -o "../../PS.Util.Terraform.dll" -buildmode=c-shared .


ENTRYPOINT ["pwsh"]
CMD []


